### ISSUE TITLE
Ducko :V

### ISSUE THREAD

**Issue by DuckMasterAl** [alecs297/alecs297.github.io#1]
I love the duck class. Thank you for this beautiful duck :duck:
https://github.com/alecs297/alecs297.github.io/blob/02543e7bf5676b705e8437c5617610cbf9374c48/index.html#L35-L59

**Comment by DuckMasterAl** [comment]
@alecs297 ^^

**Comment by alecs297** [comment]
Glad you like it! :D

**Comment by DuckMasterAl** [comment]
Might have to copy it 🤫

**Comment by alecs297** [comment]
Feel free to do so, I don't mind if you don't credit it. Just be aware it has a knife, use at your own risks!

**Comment by DuckMasterAl** [comment]
> Feel free to do so, I don't mind if you don't credit it. Just be aware it has a knife, use at your own risks!

I never noticed that xD
I guess I'll have to be careful...
